In [1]:
#Importação da biblioteca
import pandas as pd
import numpy as np

In [2]:
#Carrega a planilha
df = pd.read_csv('Walmart Inventory.csv')

In [3]:
#Amostra dos 4 primeiros itens da tabela
df.head()

,Product_ID,Product_Name,Category,Price,Stock_Quantity,Last_Updated,Supplier_Name,Supplier_Contact,Warehouse_Location,Country,State
0,6458,T-shirt,Clothing,1386.42,276,31-01-2024,Bosch,-2679856.0,E5,canada,British Columbia
1,4898,Blender,Appl.,1613.58,113,10/1/2021,Panasonic,-9815930.0,B2,United Kingdom,Scotland
2,1370,Smartphone,Mobile,1797.89,372,24/07/2022,Lenovo,-5511254.0,E5,USA,Illinois
3,9648,Microwave,Appl.,1007.11,355,3/17/2024,Asus,-7210874.0,E5,UNITED KINGDOM,England
4,1790,T-shirt,Apparel,1979.42,402,11/1/2024,Whirlpool,-2630885.0,A1,Germany,Bavaria

In [4]:
#Amostra de dados aleatórios
df.sample(10)

,Product_ID,Product_Name,Category,Price,Stock_Quantity,Last_Updated,Supplier_Name,Supplier_Contact,Warehouse_Location,Country,State
7503,2538,Laptop,Electronics,$577.39,292,8/12/2021,Bosch,-6412679.0,E5,CANADA,Quebec
8062,3480,Sofa,Furniture,251.61,255,7/4/2024,Lenovo,-8321832.0,D4,Canada,Ontario
6145,3340,T-shirt,Clothing,"$1,604.15",90,4/22/2023,HP,-4883172.0,A1,Canada,Alberta
1736,2649,TV,Electronic Devices,698.04,337,12/18/2021,Apple,-8415669.0,D4,usa,California
7622,7004,T-shirt,Cloth.,1133.75,499,7/9/2024,Panasonic,-8507814.0,A1,canada,Ontario
7389,3599,Smartphone,Mobile,$938.50,41,6/2/2022,Apple,-8147582.0,D4,UNITED KINGDOM,Wales
3658,6357,Microwave,Home,192.94,152,4/8/2022,Panasonic,-9720181.0,B2,CANADA,Ontario
3620,1304,Smartphone,Elec.,74.33,28,11/11/2023,Samsung,-3001338.0,D4,canada,Quebec
5766,9957,Sofa,Home,$116.30,22,5/29/2023,Lenovo,-6377145.0,C3,Germany,Bavaria
6591,3190,Blender,Appl.,"$1,212.52",464,7/26/2022,Lenovo,-4971132.0,A1,Canada,Alberta

In [5]:
#Sumário de dados
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Product_ID          10200 non-null  int64
 1   Product_Name        10200 non-null  str
 2   Category            10200 non-null  str
 3   Price               10200 non-null  str
 4   Stock_Quantity      10200 non-null  int64
 5   Last_Updated        10200 non-null  str
 6   Supplier_Name       10200 non-null  str
 7   Supplier_Contact    8685 non-null   float64
 8   Warehouse_Location  10200 non-null  str
 9   Country             10200 non-null  str
 10  State               10200 non-null  str
dtypes: float64(1), int64(2), str(8)
memory usage: 876.7 KB

In [6]:
#Estatística Descritiva
df.describe()

         Product_ID  Stock_Quantity  Supplier_Contact
count  10200.000000    10200.000000      8.685000e+03
mean    5461.691471      250.905882     -5.470336e+06
std     2584.316112      143.736291      2.614542e+06
min     1000.000000        0.000000     -9.999707e+06
25%     3219.750000      126.000000     -7.734583e+06
50%     5437.000000      254.000000     -5.489319e+06
75%     7659.250000      376.000000     -3.158772e+06
max     9997.000000      500.000000     -1.001551e+06

In [7]:
#Lista de linhas duplicadas
df.duplicated().sum()

np.int64(200)

In [9]:
#Inconsistência de texto nas colunas
print("\nProduct:", df["Product"].unique())
print("\nCity:", df["City"].unique())
print("\nState:", df["State"].unique())
print("\nCountry:", df["Country"].unique())

Product: <StringArray>
['Headphones',          nan,      'Table',    'T-shirt',       'Sofa',
      'Drone',         'TV',  'Chocolate',     'Laptop']
Length: 9, dtype: str

City: <StringArray>
[    'Houston',    'New York',      'Sydney',           nan,   'São Paulo',
 'Los Angeles',     'Seattle',       'Paris',      'Munich',    'Montreal',
       'Miami',     'Toronto']
Length: 12, dtype: str

State: <StringArray>
[        'Ontario',  'Rio de Janeiro',         'Bavaria',               nan,
          'Quebec',           'Texas', 'New South Wales',      'Washington',
   'Île-de-France',         'Florida',      'California',       'São Paulo',
        'New York']
Length: 13, dtype: str

Country: <StringArray>
[   'Canada',    'Brazil',   'Germany',    'CaNada',       'USA',    'canada',
 'Australia',         nan,    'France',       'usa']
Length: 10, dtype: str